d

diff --git a/S3/bash-scripts/sync b/S3/bash-scripts/sync
--- a/S3/bash-scripts/sync
+++ b/S3/bash-scripts/sync
@@ -1,1 +1,48 @@
-#!/usr/bin/ env bash
+#!/usr/bin/env bash
+
+# Exit immediately if any command returns a non-zero status
+
+set -e
+
+# Check for bucket name is provide 
+if [ -z "$1" ]; then
+    echo "There needs to provide a bucket name eg. ./bucket my-bucket-name."
+    exit 1
+fi
+
+# Check for filename prefix provide
+if [ -z "$2" ]; then
+    echo "There needs to provide a filename eg. ./file.txt."
+    exit 1
+fi
+
+BUCKET_NAME=$1
+FILENAME_PREFIX=$2
+
+# where we will store these files
+OUTPUT_DIR="/tmp/s3-bash-scripts"
+
+# remove foler if already exist.
+rm -r $OUTPUT_DIR
+
+# let create output folder
+mkdir -p $OUTPUT_DIR
+
+# generate  a random number
+# to determine how many files to create
+NUM_FILES=$((RANDOM % 6 + 5))
+
+echo "------------------Creating $NUM_FILES random files..."
+
+for((i=1; i<=$NUM_FILES; i++)); do
+    # Generate a random filename
+    FILENAME="$OUTPUT_DIR/$FILENAME_PREFIX_$i.txt"
+
+    # generate random data and write it to the file
+    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
+done
+
+tree $OUTPUT_DIR
+echo "------------------Done------------------"
+
+aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files
